### ISSUE TITLE
Enchanting bug

### ISSUE THREAD

**Issue by Yuch135** [frengor/UltimateAdvancementAPI#75]
I'm using this API in one of my plugins and I've encountered an issue and I'm wondering if it could be fixed.

I'm using the plugin ExcellentEnchants which adds new enchantments to the vanilla ones and when a player enchants something the new enchantments should appear on the enchant hint and when the player enchants, but when I enable the API the enchants stop appearing on the table.

**Comment by frengor** [comment]
Hi! Can you please provide the steps to reproduce the issue and a video showing the bug? Also, are there any errors in the server console?

**Comment by Yuch135** [comment]
- Server: paper
- Version: 1.21.1-120
- Plugins:
  - ExcellentEnchants-4.2.2
  - Nightcore-2.6.4
  - Packetevents-2.5.0
  - UltimateAdvancementAPI-2.4.1

Steps:
- Start server without UltimateAdvancementAPI.
- Try to enchant in an enchanting table (custom enchants appear).
- Stop server and install UltimateAdvancementAPI.
- Try to enchant in an enchanting table (custom enchants do not appear).


While starting the server with UltimateAdvancementAPI the following warning appears in console:
![image](https://github.com/user-attachments/assets/3952f9df-321d-47f9-a65e-f5e7e0b99c6a)

Video:
https://github.com/user-attachments/assets/f4d9f43f-d0f7-4421-8491-e21b82e13569

Thank you 😀

**Comment by frengor** [comment]
I can see in the video that you have plugman installed. Please try restarting the server completely instead of using plugins like plugman.

If that doesn't fix it, can you please provide the entire log of the server with and without UltimateAdvancementAPI installed? (preferribly using a [pastebin](https://pastebin.com/))

**Comment by Yuch135** [comment]
Tried it without plugman and still same issue.

There you go:

With UltimateAdvancementAPI: https://pastebin.com/VyLbeiL0
Without UltimateAdvancementAPI: https://pastebin.com/1qcvWhnA

**Comment by frengor** [comment]
The issue is caused by the library [CommandAPI](https://github.com/JorelAli/CommandAPI), which we use to implement commands for UltimateAdvancementAPI.
Trying to load ExcellentEnchants with just CommandAPI results in the same warning in console and custom enchantments not working. Instead, when loading a version of UltimateAdvancementAPI without commands no warnings appear and everything works fine.

My guess at what is causing the issue is that CommandAPI reloads datapacks at the end of the server initialization (see [their wiki](https://commandapi.jorel.dev/9.5.2/internal.html?highlight=reload#reloading-datapacks)), which causes minecraft to reset the loaded enchantments. If this is the case, one way to resolve the issue may be making ExcellentEnchants to re-register enchantments when this reload happens.
